version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: "./"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/pki/tls/certs:/etc/pki/tls/certs
      - /etc/pki/tls/private:/etc/pki/tls/private
  